services:
  - type: web
    name: friendlines-backend
    env: node
    region: oregon # Free tier region
    plan: free # Free tier plan
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: friendlines-backend
          property: port
    autoDeploy: false # Disable auto-deploy, use CI/CD instead
    
databases: []

# Optional: Static site for docs
# - type: static
#   name: friendlines-docs
#   env: static
#   buildCommand: echo "No build needed"
#   staticPublishPath: ./docs
#   routes:
#     - type: rewrite
#       source: /*
#       destination: /index.html 